---
API_HOSTS:
  stage:
    url: 'http://192.168.192.168'
    ip: '192.168.192.168'
    socket:
    port: 8888
    hierarchy:
      woo: '/aut_site/wp-json/wc/v3/'
      wp: '/aut_site/wp-json/wp/v2/'
  prod:
    url: 'http://192.168.192.168'
    ip: '192.168.192.168'
    socket:
    port: 8888
    hierarchy:
      woo: '/aut_site/wp-json/wc/v3/'
      wp: '/aut_site/wp-json/wp/v2/'

UI_HOSTS:
  stage:
    url: 'http://192.168.178.49:8888'
    hierarchy:
      main: '/aut_site/'
  prod:
    url: 'http://192.168.178.49:8888'
    hierarchy:
      main: '/aut_site/'

DB_HOSTS:
  stage:
    url: 'localhost'
    ip: '127.0.0.1'
    schema: aut_site_db
    table_prefix: wp_
    socket:
    port: 8889
  prod:
    url: 'localhost'
    ip: '127.0.0.1'
    schema: aut_site_db
    table_prefix: wp_
    socket:
    port: 8889
